name: Bug report
description: Report a defect or regression
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Short, clear summary.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: 1) 2) 3)
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: Logs, screenshots, or traces
      placeholder: Paste links or excerpts.
    validations:
      required: false
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser, build, commit
    validations:
      required: false
