name: Question
description: Ask a question about usage or approach
title: "Question: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: What do you want to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      placeholder: Links, logs, or background details.
    validations:
      required: false
